### ISSUE TITLE
[Feature Request] Change properties tests: to data_tests:

### ISSUE THREAD

**Issue by phil-baines-insta** [metaplane/dbt-expectations#18]
**Is your feature request related to a problem? Please describe.**
As of dbt version 1.8.X, `tests:` have been renamed to `data_tests:`
Even if users update these properties within their project, this deprecation warning message will still remain where projects use `dbt-expectations`

**Describe the solution you'd like**
Introduce a version bump which updates `tests:` to `data_tests:`

**Describe alternatives you've considered**
N/A

**Additional context**
```
16:35:10  Running with dbt=1.8.8
16:35:11  [WARNING]: Deprecated functionality
The `tests` config has been renamed to `data_tests`. Please see
https://docs.getdbt.com/docs/build/data-tests#new-data_tests-syntax for more
```

Appears within: https://github.com/search?q=repo%3Ametaplane%2Fdbt-expectations%20tests%3A&type=code

**Comment by sarahmccuan** [comment]
There are some other formatting changes that should probably be added to comply with newer versions of dbt. For example, moving things under `arguments`. 

It might be worthwhile to verify all the repo examples to match current best practices & verify that there are no deprecation warnings on the latest version of dbt. 

e.g. 

```
        data_tests:
          - dbt_expectations.expect_row_values_to_have_recent_data:
              arguments:
                datepart: day
                interval: 7
```
