### ISSUE TITLE
[Feature Request] Update example packages.yml

### ISSUE THREAD

**Issue by pgoslatara** [metaplane/dbt-expectations#3]
**Is your feature request related to a problem? Please describe.**
Thanks for taking over this package. My request is related to the example `packages.yml` as specified in the `README.md`, it looks like this:
```yaml
packages:
  - git: https://github.com/metaplane/dbt-expectations.git
    revision: bdb8f8e668da2743036a81fa95565d5787a56532
```

The use of a commit SHA, while technically a good practice, is not very intuitive for dbt developers who are used to versions and branches when it comes to pinning versions.

**Describe the solution you'd like**
I'd like to switch to version pinning. If a package is on the dbt Hub then the package can make use of constraints, e.g. `revision: [">=0.10.0", "<0.11.0"]`. For packages like this that are not on the Hub (yet!), we can only specify the exact version. I'd like to propose this:
```yaml
packages:
  - git: https://github.com/metaplane/dbt-expectations.git
    revision: 0.10.5 # Check https://github.com/metaplane/dbt-expectations/releases for the latest release
```
